// Generated by CoffeeScript 1.6.3
(function() {
  var choc, escodegen, esmorph, esprima, inspect, puts, scrubNotify, source, source_todo, _, _ref;

  _ref = require("util"), puts = _ref.puts, inspect = _ref.inspect;

  esprima = require("esprima");

  escodegen = require("escodegen");

  esmorph = require("esmorph");

  _ = require("underscore");

  choc = require("../src/choc");

  if ((typeof require !== "undefined" && require !== null) && (require.main === module)) {
    source_todo = "function add(a, b) {\n  var c = 3;\n  return a + b;\n}\n\nvar sub = function(a, b) {\n  var c = 3;\n  return a - b;\n}\nwhile (shift <= 200) {\n  // console.log(shift);\n  var x = add(1, shift);\n  shift += 14; // increment\n}";
    source = "var foo = 1;\nvar bar = foo + 2 < 3;\nif(foo + 2 < 3) {\n  console.log('it is');\n}\nconsole.log(foo);";
    source = "function add(a, b) {\n  var c = 3;\n  return a + b;\n}";
    source = "// parabolas\nvar shift = 0;\nwhile (shift <= 200) {\n  // console.log(shift);\n  var foo = shift;\n  if(foo % 2 == 0) {\n    foo = shift - 1;\n  }\n  shift += 14; // increment\n  foo = 1;\n}";
    source = "var radius = 5; \nvar x = 1;\nvar y = 2;\n\nif( (x*x) + (y*y) <= (radius*radius) ) {\n  console.log(x, y);\n}";
    scrubNotify = function(info) {
      return puts(inspect(info));
    };
    puts(choc.scrub(source, 10, {
      notify: scrubNotify
    }));
  }

}).call(this);
