// Generated by CoffeeScript 1.6.3
(function() {
  var assert, coffeeson, esprima, inspect, pp, puts, readable, testHelper, _ref;

  testHelper = require('./test_helper');

  _ref = require("util"), puts = _ref.puts, inspect = _ref.inspect;

  pp = function(x) {
    return puts(inspect(x, null, 1000));
  };

  esprima = require("esprima");

  assert = require('assert');

  readable = require("../src/readable");

  coffeeson = require("coffee-son");

  describe('Readable', function() {
    it('does', function() {
      var code, node;
      code = "__choc_trace({ lineNumber: 4, range: [ 4, 4 ], type: 'nodeType', messages: 'messagesString' });";
      return node = esprima.parse(code).body[0];
    });
    it('does something useful', function() {
      var code, node;
      code = "var foo = 0";
      node = esprima.parse(code, {
        range: true,
        loc: true
      }).body[0];
      return assert.ok(true);
    });
    return it.only('two', function() {
      var messages, node;
      messages = "[ \n  {\"lineNumber\": 1, \"message\": \"hello \" + who}\n]\n";
      messages = "var _fn = function () {\n      return true;\n    } ";
      node = esprima.parse(messages, {
        tolerant: true
      }).body[0].declarations[0].init;
      puts(messages);
      return pp(node);
    });
  });

}).call(this);
