// Generated by CoffeeScript 1.6.3
(function() {
  var assert, inspect, puts, testHelper, _ref;

  _ref = require('util'), puts = _ref.puts, inspect = _ref.inspect;

  assert = require('assert');

  testHelper = require('./test_helper');

  describe('Choc', function() {
    return it('does something useful', function() {
      return assert.ok(true);
    });
  });

}).call(this);
