// Generated by CoffeeScript 1.6.3
(function() {
  var assert, esprima, inspect, pp, puts, readable, should, testHelper, _ref;

  testHelper = require('./test_helper');

  _ref = require("util"), puts = _ref.puts, inspect = _ref.inspect;

  pp = function(x) {
    return puts(inspect(x, null, 1000));
  };

  esprima = require("esprima");

  assert = require('assert');

  should = require("should");

  readable = require("../src/readable");

  describe('Readable', function() {
    var message, messageE;
    message = function(code) {
      var nodes;
      nodes = esprima.parse(code, {
        range: true,
        loc: true
      }).body[0];
      pp(nodes);
      return readable.readableNode(nodes);
    };
    messageE = function(code) {
      return eval(code + "; " + message(code));
    };
    it('simple assignment', function() {
      var code;
      code = "var foo = 0";
      return messageE(code)[0].message.should.eql('Create the variable <span class="choc-variable">foo</span> and set it to <span class="choc-value">0</span>');
    });
    it('assignment and increment', function() {
      var code;
      code = "foo = 1 + bar";
      return pp(message(code));
    });
    return it.only('function calls', function() {
      var code;
      code = "console.log('hello')";
      return pp(message(code));
    });
  });

}).call(this);
